### ISSUE TITLE
2017-08-09 

### ISSUE THREAD

**Issue by lynring24** [lynring24/ITimeU#13]
- 통계 UI
- 전체적인 UI
- 현재 진행 상태
- TODO

**Comment by lynring24** [comment]
[통계]
- 기간 : 오늘을 기준으로 back N
- custom : Date Range 사용 -> 기간 구현은 적용시키면서 알아보겠음

**Comment by snowflake-1117** [comment]
[전체적인 UI]
* 리스트와 타이머는 MainActivity에 붙여서 스왑가능하게 함
* 하단 탭 바를 통해 리스트/어바웃/통계/설정 으로 이동할 수 있음(하단에 계속 보임)
