### ISSUE TITLE
2017-08-16

### ISSUE THREAD

**Issue by lynring24** [lynring24/ITimeU#14]
1. swap 처리 여부와 그에 따른 디자인 및 fragmnet/activity 여부 변동 
2. app을 back으로 돌림 여부 -> Thread로 처리
3. 이번주에 어디까지 개발할지(오늘 ~ 다음주 화), 얼만큼 개발했는지
~4. Intent의 중첩 처리-> Intent Flag~

**Comment by lynring24** [comment]
1-a) click -> 4개의 activity(main, setting, stat, about) & 2 frag (timer , list )-> main
`1-b) swap -> nav bar icon 5개 추가`

**Comment by jiunoh** [comment]
알람 (권한, 설정에서 소리/진동/웨이크록 받아오기, 알람 울리기) + 설정 데이터 저장

**Comment by lynring24** [comment]
~* timer thread 완성~
~* timer data 처리~
~* nav bar 수정 ~
~->다음주 화요일~

**Comment by snowflake-1117** [comment]
To Do<br />
~1. 뷰페이저 구현하기~
~2. 리스트뷰 프래그먼트로 변경~
~3. 리스트 아이템 클릭 시 타이머로 이동하는 함수 구현(데이터 이동 포함)~
4. 리스트 아이템 status에 따른 아이템 모양 변경 => 다음 주에 할 예정

**Comment by snowflake-1117** [comment]
~5. About 구현~
~6. 통계 구현~
