### ISSUE TITLE
Timer Fragment data store time changed(might be)

### ISSUE THREAD

**Issue by lynring24** [lynring24/ITimeU#15]
~Table for TimerFragment  : Timer~

**Comment by lynring24** [comment]
Timer 완료 시 , unit 증가

**Comment by lynring24** [comment]
간단한 숫자 하나를 저장하는것이므로 sharedPreference를 사용하겠습니다.

**Comment by snowflake-1117** [comment]
unit에 대해 sharedPreference를 쓴다는 뜻인가요?ㅁ? 일단 unit 값을 타이머에서 받도록 설정은 해놨습니다만, 만약 그편이 합리적이라면 그렇게 처리해주세요!

**Comment by lynring24** [comment]
timer frag에서 써야하는 count 정보를 shared Preference로 사용할 겁니다. 
아마 지은님 도 그걸로 저장하는걸로 알고있습니다 .

**Comment by snowflake-1117** [comment]
아하 이해했습니당!
