### ISSUE TITLE
[Setting] sharedPreference 부분이 조금 바꼈습니다. 

### ISSUE THREAD

**Issue by lynring24** [lynring24/ITimeU#37]
@charis227 
#33 
SharedPreference를 아예 따로 클래스로 뺐고, timerFragment와 SettingFragment에 적용을 마쳤습니다 .
TimerBranch를 확인해주세요
![example](/Setting_Preview/pref.png)

**Comment by snowflake-1117** [comment]
Example 페이지가 404입니당 ㅜㅜ
