### ISSUE TITLE
타이머에서 목록으로 넘어가는 action

### ISSUE THREAD

**Issue by lynring24** [lynring24/ITimeU#4]
좌우로 스왑하는 방식 vs  메뉴바로 이동

전자가 더 직관적인거 같긴 하고, @snow-flake1117이 얘기했던 fragment를 적용
메뉴 바 > 세팅, 통계,about 이 들어감 

※ app의 메인 화면은 그대로 timer로 쓰는지 의논

**Comment by snowflake-1117** [comment]
일단 메뉴바 이동으로 하게끔 list 코드는 리버트 해뒀어요!

스왑 방식 넣는 건 그리 복잡한 일이 아니니 일단 메뉴바 이동을 디폴트로 해보고
프로토타입이 완성되면 그때 봐서 바꾸거나 해도 괜찮을듯 합니다.

메인화면도 마찬가지 맥락이라고 생각합니다만 그대로 가면 될 것 같습니다 :+1:

**Comment by jiunoh** [comment]
투두리스트는 좌우스왑으로, 세팅과 통계는 메뉴바로 하는 게 좋다고 생각.  그편이 직관적이기도 하고 타이머와 투두가 가장 많이 접근하게 되는 화면이기 때문에? (설정은 거의 들어갈 일 없고 통계도 리스트만큼 자주 보지는 않을 것으로 생각됨)

**Comment by snowflake-1117** [comment]
스와이프로 귀결 땅땅
