### ISSUE TITLE
read me 파일 남아있으면 올려주세요

### ISSUE THREAD

**Issue by lynring24** [lynring24/ITimeU#6]
저번 레포 날리면서 readMe도 같이 날라갔나 봅니다 .
코드 규칙은 wiki / read Me 중 어디에 올리는 게 맞을까요

**Comment by snowflake-1117** [comment]
제게도 리드미가 없습니다.(ㅜㅜ)
코드 규칙은 위키에 올리는 게 맞다고 생각하구요!

**Comment by lynring24** [comment]
반영해 뒀습니다.
