### ISSUE TITLE
[디자인] 메인 화면을 무엇으로 하면 좋은가?

### ISSUE THREAD

**Issue by lynring24** [lynring24/ITimeU#7]
*1. 리스트로 시작 시, 사용자가 하려는 목록을 추가하는 과정이 자연스럽다*
*2. 타이머로 시작 시, 직관적이다*

라는 장점이 있습니다. 
앱을 처음 실행할 때 어떤 화면이 가장 먼저 나오는게 좋은지는 진행하면서 계속 바뀔 것 같습니다 .

**Comment by snowflake-1117** [comment]
a. 타이머에서 바로 start를 할 수 있다(리스트와 독립적으로) -> 타이머 메인
b. 그렇지 않다 -> 리스트 메인

a의 경우는 달성률을 관리하기가 어렵고, b의 경우는 보다 간단히 달성률을 관리할 수 있습니다.

**Comment by jiunoh** [comment]
할일을 정해두고 시작하는 편이 아닌 편보다 많을 것으로 예상되기 때문에, 1의 경우가 더 나을 것으로 생각.
+ (리스트 메인에서 왼쪽으로 스왑하면 타이머, 타이머에서 오른쪽으로 스왑하면 리스트가 나오는 게 왠지 더 직관적일 것 같음)

**Comment by snowflake-1117** [comment]
그러면 1로 한다고 할 경우,
1) 시간을 달성률에 추가할 것인지 혹은 버릴 것인지
2) 이름을 입력 받을 것인지 혹은 아닌지

**Comment by jiunoh** [comment]
1. 추가하는 쪽에 한 표
2. 이름이 태스크 이름을 뜻한다면 있는 편이 좋다고 여겨짐

**Comment by lynring24** [comment]
시작 : 리스트
[안건]
메뉴바를 밑으로 두면 list 타이머 둘다 메뉴바를 적용하기 좋을 것 같습니다

**Comment by snowflake-1117** [comment]
@charis227 추가한다는 게 무슨뜻인가요?

**Comment by jiunoh** [comment]
만일 사용자가 태스크1을 3회 하고 태스크2를 2단원 한다고 설정한 후 태스크1은 1회만 하고 태스크2는 2단원 다 했다고 하면 달성률은 3/5로 하는 게 맞지 않을까요..?

**Comment by snowflake-1117** [comment]
맞습니다

**Comment by jiunoh** [comment]
시간을 달성률에 추가한다==저 뜻

**Comment by snowflake-1117** [comment]
시간을 달성률에 추가할 필요가 있나욤?ㅁ?

**Comment by jiunoh** [comment]
아무튼 하기로 목표한 바이기 때문에 말 그대로 달성했는지 아닌지를 보여주는 취지에서 나쁘지 않다고 생각합니당

**Comment by snowflake-1117** [comment]
그런데 아까 저희 얘기할 때,
포모도로 취지엔 세션 갯수가 달성률과 연관이 있다고 생각해서 시간은 이미 빼기로 하지 않았나욤?

**Comment by jiunoh** [comment]
세션 개수==시간으로 생각하고 말하고 있었읍니다...

**Comment by snowflake-1117** [comment]
아하 이해했습니다. 세션 개수는 달성률과 함께 보여질 예정입니다!

**Comment by snowflake-1117** [comment]
그러면 '리스트를 메인으로+세션 개수와 달성률 같이 보이기'로 귀결입니다.
