### ISSUE TITLE
[디자인] 메뉴바의 위치 이동 

### ISSUE THREAD

**Issue by lynring24** [lynring24/ITimeU#8]
메뉴바 (내비게이션 바) 하단에  #배치함으로써, 타이머와 리스트 모두 메뉴바를 사용할 수 있게 됩니다.

**Comment by snowflake-1117** [comment]
찬성찬성 :+1: :1st_place_medal:

**Comment by jiunoh** [comment]
타이머와 리스트 모두 메뉴바를 사용한다는 게 이해가 가지 않습니당 (리스트도 메뉴바를 통해 접근한다는 것인지?)

**Comment by snowflake-1117** [comment]
[링크](https://www.google.co.kr/search?biw=1135&bih=879&tbm=isch&sa=1&q=%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C+%ED%83%AD&oq=%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C+%ED%83%AD&gs_l=psy-ab.3..0l4.13504.15385.0.15542.10.7.3.0.0.0.127.792.0j7.7.0....0...1.1j4.64.psy-ab..0.10.815...0i13k1.XOEbDymmEEE)
이걸 보시면 이해가 가실겁니당

**Comment by jiunoh** [comment]
탭을 이용해 타이머와 리스트를 접근한다는 이야기인가요? 그리고 탭은 상단이 아니라 하단에 배치...?

**Comment by snowflake-1117** [comment]
네네 하단에 배치할 예정으로 화면구성도는 슬랙에 올려드릴게여

**Comment by jiunoh** [comment]
하지만 내비게이션 바는 하단보다 상단에 있는 편이 접근하기도 편하고 눈에 잘 띄지 않을지 ?ㅁ?

**Comment by snowflake-1117** [comment]
그렇게하면 상단이 너무 무거워져서 하단으로 생각했는데 클릭하는건 하단이 더 편해여
