### ISSUE TITLE
[통계] 진행상황

### ISSUE THREAD

**Issue by lynring24** [lynring24/ITimeU#9]
input : 단위
-> dropdown / radio / text / seekbar

output: 달성률 , 그래프

**Comment by snowflake-1117** [comment]
### 1. Input
1-1. 먼저 week/month/custom의 대분류는 SelectBox를 통해 아래와 같이 선택할 수 있도록 하면 될 것 같습니다.
<image src="http://www.appsapk.com/wp-content/uploads/2015/01/ClearFocus-Pomodoro-Timer-2.png"/>

1-2. 그리고 custom 내부에서는 1) 시작날짜와 끝 날짜를 EditText로 둔 뒤, 각각을 클릭하면 달력 다이얼로그를 띄우도록 코드를 작성하거나, 2) 마찬가지로 SelectBox를 사용해도 무관합니다.

> Q. 커스텀 기간에 제한을 둬야 할 것 같습니다만(그래프 출력의 문제) 제 생각이 맞나요? 맞다면, 최대 기간을 어느 정도로 생각하시나요? 저는 약 한 달을 최대로 두는 게 구현하는데에 지장이 덜 될 것이라고 생각합니다!

### 2. Output
2-1. 그래프
이런 식의 꺾은선 그래프를 추천합니다.
<image src="https://i.stack.imgur.com/eCddi.png"/>

검색해보니 API는 [MPAndroidChart](https://github.com/PhilJay/MPAndroidChart)를 대개 추천하더군요.

2-2. 달성률
달성률은 그래프 아래에 텍스트로 보여주는 게 직관적이고 편하지 않을까요.
`완료한 포모도로 수: ?/ 계획한 총 포모도로 수: ?/하루 평균 마친 포모도로 수: ?`
와 같은 대략적 포맷을 사용하면 될 듯합니다.

**Comment by lynring24** [comment]
Q1. 확률(%)로 표기하기로 하지 않았나요
Q2. 그래프의 개수 (2개로 나눠서 표현할 것인지) 

~출력 가능한 기간은 프로토타입 만들어지는대로 다시 이슈 올리겠습니다(이건 디자인 이슈니까요)~

*참고하고 있는 open source*
* MP Android Chart
* google chart
* hello-chart-andoird

**Comment by snowflake-1117** [comment]
Q1 -> 아 저건 저런식으로 텍스트 보여주라는 의미라 퍼센티지로 하셔도 몹시 괜찮습니다
Q2 -> 1개면 충분하지 않을까요? 굳이 2개를 보여주지 않아도 될 것 같습니다 ~절대 귀찮아서가 아님~

**Comment by snowflake-1117** [comment]
통계 화면에는 Unit, Total unit 의 두 가지 꺾은선 그래프가 나타납니다.

1. Week: 오늘을 기점으로 이전 7일 간의 통계를 보여줍니다.
<img src="https://user-images.githubusercontent.com/19372511/29602466-40989438-881b-11e7-805e-25611fd875d8.png" width="300"/>
2. Month: 오늘을 기점으로 이전 1달 간의 통계를 보여줍니다.
<img src="https://user-images.githubusercontent.com/19372511/29602468-409b6758-881b-11e7-9c0d-85fbfd28c97a.png" width="300"/>
3. Custom: 사용자가 날짜를 커스텀 할 수 있습니다. 다만 시작 기간과 끝 기간의 차이는 1일 이상이어야 합니다.
<img src="https://user-images.githubusercontent.com/19372511/29602465-409801b2-881b-11e7-9dfb-64c82f3aba3e.png" width="300"/>
<img src="https://user-images.githubusercontent.com/19372511/29602464-40850e2c-881b-11e7-88ef-5086d4a5b786.png" width="300"/>
<img src="https://user-images.githubusercontent.com/19372511/29602670-13a8befc-881c-11e7-85aa-2400813bcc1f.png" width="300"/>

디자인, 상호작용 기능은 추후 추가 예정

**Comment by snowflake-1117** [comment]
<img src="https://user-images.githubusercontent.com/19372511/29619582-6324aef2-8856-11e7-87f8-444ab3a535a0.png" width="300"/>
애니메이션 & 디자인 적용 완료

**Comment by snowflake-1117** [comment]
<최종본>
- 여백 조절
- mark view 적용 
<img src="https://user-images.githubusercontent.com/19372511/29646141-9c8fba72-88bc-11e7-9686-22c97ebb10a7.png" width="300"/>

**Comment by lynring24** [comment]
확인했습니다.

**Comment by snowflake-1117** [comment]
- 커스텀 시작 날짜/끝 날짜에 대한 힌트 스트링 추가
- 커스텀 날짜 2회 이상 생성 시, 시작 날짜와 끝 날짜 중 한 날짜만 입력받아도 차트가 그려지는 버그 수정
